# Generated by Django 3.1.7 on 2021-04-29 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=1000)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('indate', models.DateTimeField(default=datetime.date.today)),
                ('outdate', models.DateTimeField(default=datetime.date.today)),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
                ('gender', models.CharField(max_length=10)),
                ('adult', models.CharField(max_length=20)),
                ('children', models.CharField(max_length=20)),
                ('c1', models.BooleanField(default=False)),
                ('c2', models.BooleanField(default=False)),
                ('c3', models.BooleanField(default=False)),
                ('c4', models.BooleanField(default=False)),
                ('c5', models.BooleanField(default=False)),
                ('total', models.BooleanField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'hotel_checkin',
            },
        ),
    ]
