# Generated by Django 3.1.7 on 2021-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='total',
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
