# Generated by Django 3.1.7 on 2021-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210429_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
